apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0.6
        resources:
        ports:
        - containerPort: 27017
        volumeMounts:   
          - name: mongo-persistent-storage
            mountPath: /var/lib/mongo
      volumes:  
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim  

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP 
    nodePort: 31048
    

